# Site settings

title: Head in the stars # Title of your site
email: # Your contant email
tagline: a blog by Jay Qi
copyright: Jay Qi

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.jayqi.com" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     jayyqi  # Replace this with your Twitter username
github_username:      jayqi  # Replace this with your GitHub username
linkedin_username:    jayqi  # Replace this with your LinkedIn username
google_plus_username:   # Replace this with your Google+ username
facebook_username:      # Replace this with your Facebook username
dribbble_username:      # Replace this with your Dribbble username

# Build settings
markdown: kramdown

# Gibhub defaults
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

# Github settings -- can't change
lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
